name: Build C Code

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: configure the code
        run: ./configure
        
      - name: Build the code
        run: make

      - name: Install the code
        run: make install

      - name: Run test script
        run: cd tests && ./dw-tests.sh
